In [1]:
# PyTorch向量demo
# 导入模块
import torch as T
import numpy as np

In [3]:
# 检测是否为PyTorch中的向量（Tensor）
x = [12, 23, 34, 45, 56, 67, 78, 89]
# checks whether the object is a tensor object
print(T.is_tensor(x))
# checks whether the object is stored as tensor object
print(T.is_storage(x))

False
False


In [4]:
y = T.randn(1, 2, 3)
print(y)
print(T.is_tensor(y))
print(T.is_storage(y))
# size of tensor
print(y.size())
# the total number of elements in the input tensor
print(T.numel(y))

tensor([[[-0.4199, -0.4139,  0.6227],
         [-0.6734, -0.8894,  0.3225]]])
True
False
torch.Size([1, 2, 3])
6


In [5]:
# zeros函数
z = T.zeros(4, 4)
print(z)
print(z.size())
print(T.numel(z))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([4, 4])
16


In [6]:
# eye函数
w1 = T.eye(3, 4)
print(w1)
print(w1.size())
print(T.numel(w1))
w2 = T.eye(5, 4)
print(w2)
print(w2.size())
print(T.numel(w2))

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])
torch.Size([3, 4])
12
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])
torch.Size([5, 4])
20


In [8]:
# Torch can read from a NumPy array format, not list
x1 = np.array(x)
t = T.from_numpy(x1)
print(t)
print(T.is_tensor(t))
print(T.is_storage(t))

tensor([12, 23, 34, 45, 56, 67, 78, 89])
True
False


In [9]:
# Torch Tensor convert to numpy.ndarrays
print(t.data)
print(type(t))
print(type(t.data))
x2 = t.numpy()
print(x2)
print(type(x2))

tensor([12, 23, 34, 45, 56, 67, 78, 89])
<class 'torch.Tensor'>
<class 'torch.Tensor'>
[12 23 34 45 56 67 78 89]
<class 'numpy.ndarray'>


In [10]:
# 利用Tensor函数构建tensor
tensor1 = T.Tensor([[1, 2, 3], [4, 5, 6]])
print(tensor1)
print(T.is_tensor(tensor1))
print(T.is_storage(tensor1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
True
False


In [11]:
# linspace in pytorch
print(T.linspace(2, 10, steps=9))
# logarithmic spacing
print(T.logspace(start=-10, end=10, steps=5))

tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])


In [13]:
# random numbers from a uniform distribution between the values 0 and 1
print(T.rand(10))
print(T.rand(4, 5))

tensor([0.6654, 0.0334, 0.3522, 0.2388, 0.1594, 0.5571, 0.5282, 0.0241, 0.7410,
        0.6273])
tensor([[0.3108, 0.5514, 0.3539, 0.2441, 0.0871],
        [0.9125, 0.6161, 0.4074, 0.6260, 0.7564],
        [0.7621, 0.4389, 0.6552, 0.9586, 0.2361],
        [0.9228, 0.2407, 0.4747, 0.5336, 0.2194]])


In [14]:
# selecting values from a range, called random permutation
print(T.randperm(6))
print(T.randperm(8))

tensor([5, 2, 1, 4, 0, 3])
tensor([2, 7, 6, 4, 0, 5, 3, 1])


In [16]:
# usage of range function
print(T.arange(10, 20))
print(T.arange(10, 30, 3))

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
tensor([10, 13, 16, 19, 22, 25, 28])


In [18]:
# find maximum and minimum of tensor
d = T.randn(4, 5)
print(d)
# dim: 0 means along the column, 1 row
print(T.argmin(d, dim=0))
print(T.argmax(d, dim=1))

tensor([[-0.2512,  1.4601,  0.9010,  0.7730, -0.7425],
        [-0.6755, -0.5227, -0.5243, -0.4742, -0.0601],
        [-0.5485, -0.9667,  0.2066, -0.7650, -1.0527],
        [-1.6763,  1.5784, -0.5299,  0.0463, -0.8977]])
tensor([3, 2, 3, 2, 2])
tensor([1, 4, 2, 1])


In [19]:
# concatenate two tensors
t1 = T.randn(2, 4)
t2 = T.randn(3, 4)
print(T.cat((t1, t2)))

tensor([[-0.7261, -0.8325,  1.2299,  0.7616],
        [-0.4920,  0.5611,  1.2690,  0.1944],
        [-0.7799, -0.1575,  0.1591,  1.5869],
        [ 1.8982,  0.3544,  1.2835,  0.5460],
        [-0.3167,  1.4114,  0.0480, -1.7889]])


In [21]:
# A tensor can be split between multiple chunks
a = T.randn(4, 6)
print(a)
# 0 means row, 1 column, default: 0
print(T.chunk(a, 2, 0))
print(T.chunk(a, 3, 1))

tensor([[-2.5663,  0.6231, -0.4205, -1.3815, -0.1627,  0.4648],
        [ 0.2757, -0.1346,  0.7227,  0.8774,  0.2984,  0.8735],
        [-0.3269,  0.4889, -0.3513,  0.0331,  0.4255,  0.5229],
        [-0.8490,  0.1852,  1.0790, -1.6085, -0.9337, -1.3909]])
(tensor([[-2.5663,  0.6231, -0.4205, -1.3815, -0.1627,  0.4648],
        [ 0.2757, -0.1346,  0.7227,  0.8774,  0.2984,  0.8735]]), tensor([[-0.3269,  0.4889, -0.3513,  0.0331,  0.4255,  0.5229],
        [-0.8490,  0.1852,  1.0790, -1.6085, -0.9337, -1.3909]]))
(tensor([[-2.5663,  0.6231],
        [ 0.2757, -0.1346],
        [-0.3269,  0.4889],
        [-0.8490,  0.1852]]), tensor([[-0.4205, -1.3815],
        [ 0.7227,  0.8774],
        [-0.3513,  0.0331],
        [ 1.0790, -1.6085]]), tensor([[-0.1627,  0.4648],
        [ 0.2984,  0.8735],
        [ 0.4255,  0.5229],
        [-0.9337, -1.3909]]))


In [23]:
# The gather function collects elements from a tensor and places it in another tensor using an index argument.
# The index position is determined by the LongTensor function in PyTorch.
b = T.gather(T.Tensor([[11, 12], [23, 24]]), 1, T.LongTensor([[0, 0], [1, 0]]))
print(b)

tensor([[11., 11.],
        [24., 23.]])


In [24]:
# The LongTensor function or the index select function can be used to fetch relevant values from a tensor.
c = T.randn(4, 4)
print(c)
indices = T.LongTensor([0, 2])
print(T.index_select(c, 0, indices))
print(T.index_select(c, 1, indices))

tensor([[-1.0463,  0.8661, -0.6331, -0.5752],
        [-0.8758, -0.2882,  0.2911, -1.9206],
        [-0.7444, -0.3329,  0.0287, -0.2793],
        [-1.2515, -2.5879,  0.3839,  0.2269]])
tensor([[-1.0463,  0.8661, -0.6331, -0.5752],
        [-0.7444, -0.3329,  0.0287, -0.2793]])
tensor([[-1.0463, -0.6331],
        [-0.8758,  0.2911],
        [-0.7444,  0.0287],
        [-1.2515,  0.3839]])


In [25]:
# identify non-zero elements in a tensor
print(T.nonzero(T.Tensor([10, 0, 23, 0, 20, 0])))

tensor([[0],
        [2],
        [4]])


In [26]:
# splitting the tensor into small chunks
print(T.split(T.Tensor([12, 21, 34, 32, 45, 54, 56, 65]), 2))
print(T.split(T.Tensor([12, 21, 34, 32, 45, 54, 56, 65]), 3))

(tensor([12., 21.]), tensor([34., 32.]), tensor([45., 54.]), tensor([56., 65.]))
(tensor([12., 21., 34.]), tensor([32., 45., 54.]), tensor([56., 65.]))


In [27]:
# transpose
e = T.randn(2, 3)
print(e)
print(e.t())
print(e.transpose(1, 0))

tensor([[ 0.8518,  0.1776, -0.5511],
        [ 0.1719, -1.2110,  0.4988]])
tensor([[ 0.8518,  0.1719],
        [ 0.1776, -1.2110],
        [-0.5511,  0.4988]])
tensor([[ 0.8518,  0.1719],
        [ 0.1776, -1.2110],
        [-0.5511,  0.4988]])


In [28]:
# unbind:  removes a dimension from a tensor
# 0 row, 1 column, default: 0
f = T.randn(2, 3)
print(f)
print(T.unbind(f, 1))
print(T.unbind(f, 0))

tensor([[-1.9928,  0.0541,  1.7332],
        [ 1.8179, -0.5556, -0.6515]])
(tensor([-1.9928,  1.8179]), tensor([ 0.0541, -0.5556]), tensor([ 1.7332, -0.6515]))
(tensor([-1.9928,  0.0541,  1.7332]), tensor([ 1.8179, -0.5556, -0.6515]))


In [30]:
# math function
T.manual_seed(1234)
g = T.randn(2, 3)
print(g)

tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [31]:
# add function
T.add(g, 20)

tensor([[20.0461, 20.4024, 18.9885],
        [20.2167, 19.3877, 20.5036]])

In [34]:
# ceil function
T.ceil(g)

tensor([[ 1.,  1., -1.],
        [ 1., -0.,  1.]])

In [35]:
# floor function
T.floor(g)

tensor([[ 0.,  0., -2.],
        [ 0., -1.,  0.]])

In [36]:
# exp function
T.exp(g)

tensor([[1.0472, 1.4954, 0.3637],
        [1.2420, 0.5421, 1.6547]])

In [37]:
# sigmoid function
T.sigmoid(g)

tensor([[0.5115, 0.5993, 0.2667],
        [0.5540, 0.3515, 0.6233]])

In [41]:
# 矩阵的点乘, x.mul(y) 或者 x * y
h = T.FloatTensor([[1,2], [3,4], [5, 6]])
print(h)
print(h.mul(h))
print(h * h)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 1.,  4.],
        [ 9., 16.],
        [25., 36.]])
tensor([[ 1.,  4.],
        [ 9., 16.],
        [25., 36.]])


In [42]:
# 矩阵相乘, x.mm(y)
print(h.mm(h.t()))

tensor([[ 5., 11., 17.],
        [11., 25., 39.],
        [17., 39., 61.]])
