In [1]:
# PyTorch向量demo
# 导入模块
import torch as T
import numpy as np

In [2]:
# 检测是否为PyTorch中的向量（Tensor）
x = [12, 23, 34, 45, 56, 67, 78, 89]
# checks whether the object is a tensor object
print(T.is_tensor(x))
# checks whether the object is stored as tensor object
print(T.is_storage(x))

False
False


In [3]:
y = T.randn(1, 2, 3)
print(y)
print(T.is_tensor(y))
print(T.is_storage(y))
# size of tensor
print(y.size())
# the total number of elements in the input tensor
print(T.numel(y))

tensor([[[-0.1136, -0.5851, -2.6308],
         [ 0.1024,  0.5212, -0.8174]]])
True
False
torch.Size([1, 2, 3])
6


In [4]:
# zeros函数
z = T.zeros(4, 4)
print(z)
print(z.size())
print(T.numel(z))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([4, 4])
16


In [5]:
# eye函数
w1 = T.eye(3, 4)
print(w1)
print(w1.size())
print(T.numel(w1))
w2 = T.eye(5, 4)
print(w2)
print(w2.size())
print(T.numel(w2))

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])
torch.Size([3, 4])
12
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])
torch.Size([5, 4])
20


In [6]:
# Torch can read from a NumPy array format, not list
x1 = np.array(x)
t = T.from_numpy(x1)
print(t)
print(T.is_tensor(t))
print(T.is_storage(t))

tensor([12, 23, 34, 45, 56, 67, 78, 89], dtype=torch.int32)
True
False


In [7]:
# Torch Tensor convert to numpy.ndarrays
print(t.data)
print(type(t))
print(type(t.data))
x2 = t.numpy()
print(x2)
print(type(x2))

tensor([12, 23, 34, 45, 56, 67, 78, 89], dtype=torch.int32)
<class 'torch.Tensor'>
<class 'torch.Tensor'>
[12 23 34 45 56 67 78 89]
<class 'numpy.ndarray'>


In [8]:
# 利用Tensor函数构建tensor
tensor1 = T.Tensor([[1, 2, 3], [4, 5, 6]])
print(tensor1)
print(T.is_tensor(tensor1))
print(T.is_storage(tensor1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
True
False


In [9]:
# linspace in pytorch
print(T.linspace(2, 10, steps=9))
# logarithmic spacing
print(T.logspace(start=-10, end=10, steps=5))

tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])


In [10]:
# random numbers from a uniform distribution between the values 0 and 1
print(T.rand(10))
print(T.rand(4, 5))

tensor([0.6592, 0.7289, 0.2897, 0.0683, 0.7685, 0.1479, 0.4261, 0.7441, 0.6307,
        0.1431])
tensor([[0.3558, 0.0859, 0.6212, 0.3092, 0.2453],
        [0.8888, 0.2677, 0.1193, 0.3646, 0.6129],
        [0.2085, 0.8565, 0.2590, 0.9823, 0.4127],
        [0.6002, 0.0363, 0.8779, 0.0213, 0.9232]])


In [11]:
# selecting values from a range, called random permutation
print(T.randperm(6))
print(T.randperm(8))

tensor([0, 4, 5, 3, 2, 1])
tensor([0, 5, 4, 6, 2, 1, 7, 3])


In [12]:
# usage of range function
print(T.arange(10, 20))
print(T.arange(10, 30, 3))

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
tensor([10, 13, 16, 19, 22, 25, 28])


In [13]:
# find maximum and minimum of tensor
d = T.randn(4, 5)
print(d)
# dim: 0 means along the column, 1 row
print(T.argmin(d, dim=0))
print(T.argmax(d, dim=1))

tensor([[ 0.9217, -0.1068, -0.5859, -1.0494,  0.2641],
        [-1.6827, -0.5163, -1.7808, -0.2379,  0.5144],
        [ 1.9446,  0.3222, -1.3181,  1.0982,  1.8044],
        [-1.7152,  0.6346,  1.4222, -1.9336, -0.0098]])
tensor([3, 1, 1, 3, 3])
tensor([0, 4, 0, 2])


In [14]:
# concatenate two tensors
t1 = T.randn(2, 4)
t2 = T.randn(3, 4)
print(T.cat((t1, t2)))

tensor([[-1.1295,  1.7040, -0.7701, -0.7643],
        [-0.5417,  0.1874,  0.7582, -0.9736],
        [ 0.4867,  1.0103, -1.7306, -0.0214],
        [ 0.1821,  1.6806, -1.1346, -0.0921],
        [ 0.9963,  0.1677,  0.5886, -0.7600]])


In [15]:
# A tensor can be split between multiple chunks
a = T.randn(4, 6)
print(a)
# 0 means row, 1 column, default: 0
print(T.chunk(a, 2, 0))
print(T.chunk(a, 3, 1))

tensor([[ 0.4041,  0.2816, -1.3620, -0.4796, -0.6298, -0.1119],
        [-0.1132,  0.4680, -0.9488, -2.3916, -0.2324,  0.1824],
        [ 2.6004,  1.1676,  2.0935,  1.0246,  0.6111, -0.1336],
        [-0.4433,  0.4704, -0.3779, -2.1943,  1.3298, -0.9534]])
(tensor([[ 0.4041,  0.2816, -1.3620, -0.4796, -0.6298, -0.1119],
        [-0.1132,  0.4680, -0.9488, -2.3916, -0.2324,  0.1824]]), tensor([[ 2.6004,  1.1676,  2.0935,  1.0246,  0.6111, -0.1336],
        [-0.4433,  0.4704, -0.3779, -2.1943,  1.3298, -0.9534]]))
(tensor([[ 0.4041,  0.2816],
        [-0.1132,  0.4680],
        [ 2.6004,  1.1676],
        [-0.4433,  0.4704]]), tensor([[-1.3620, -0.4796],
        [-0.9488, -2.3916],
        [ 2.0935,  1.0246],
        [-0.3779, -2.1943]]), tensor([[-0.6298, -0.1119],
        [-0.2324,  0.1824],
        [ 0.6111, -0.1336],
        [ 1.3298, -0.9534]]))


In [16]:
# The gather function collects elements from a tensor and places it in another tensor using an index argument.
# The index position is determined by the LongTensor function in PyTorch.
b = T.gather(T.Tensor([[11, 12], [23, 24]]), 1, T.LongTensor([[0, 0], [1, 0]]))
print(b)

tensor([[11., 11.],
        [24., 23.]])


In [17]:
# The LongTensor function or the index select function can be used to fetch relevant values from a tensor.
c = T.randn(4, 4)
print(c)
indices = T.LongTensor([0, 2])
print(T.index_select(c, 0, indices))
print(T.index_select(c, 1, indices))

tensor([[-0.2646, -0.8973,  0.6894, -0.0195],
        [-0.1933,  2.3623, -0.6644,  0.5033],
        [ 0.1891,  0.7503,  0.7995,  1.7826],
        [-1.0849, -0.3725, -1.2520, -0.3625]])
tensor([[-0.2646, -0.8973,  0.6894, -0.0195],
        [ 0.1891,  0.7503,  0.7995,  1.7826]])
tensor([[-0.2646,  0.6894],
        [-0.1933, -0.6644],
        [ 0.1891,  0.7995],
        [-1.0849, -1.2520]])


In [18]:
# identify non-zero elements in a tensor
print(T.nonzero(T.Tensor([10, 0, 23, 0, 20, 0])))

tensor([[0],
        [2],
        [4]])


In [19]:
# splitting the tensor into small chunks
print(T.split(T.Tensor([12, 21, 34, 32, 45, 54, 56, 65]), 2))
print(T.split(T.Tensor([12, 21, 34, 32, 45, 54, 56, 65]), 3))

(tensor([12., 21.]), tensor([34., 32.]), tensor([45., 54.]), tensor([56., 65.]))
(tensor([12., 21., 34.]), tensor([32., 45., 54.]), tensor([56., 65.]))


In [20]:
# transpose
e = T.randn(2, 3)
print(e)
print(e.t())
print(e.transpose(1, 0))

tensor([[ 1.0061,  1.4701, -0.9887],
        [-1.4675,  1.7748,  1.8624]])
tensor([[ 1.0061, -1.4675],
        [ 1.4701,  1.7748],
        [-0.9887,  1.8624]])
tensor([[ 1.0061, -1.4675],
        [ 1.4701,  1.7748],
        [-0.9887,  1.8624]])


In [21]:
# unbind:  removes a dimension from a tensor
# 0 row, 1 column, default: 0
f = T.randn(2, 3)
print(f)
print(T.unbind(f, 1))
print(T.unbind(f, 0))

tensor([[ 0.1357,  0.6004,  2.0958],
        [-2.0174, -0.4341, -0.3915]])
(tensor([ 0.1357, -2.0174]), tensor([ 0.6004, -0.4341]), tensor([ 2.0958, -0.3915]))
(tensor([0.1357, 0.6004, 2.0958]), tensor([-2.0174, -0.4341, -0.3915]))


In [22]:
# math function
T.manual_seed(1234)
g = T.randn(2, 3)
print(g)

tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [23]:
# add function
T.add(g, 20)

tensor([[20.0461, 20.4024, 18.9885],
        [20.2167, 19.3877, 20.5036]])

In [24]:
# ceil function
T.ceil(g)

tensor([[ 1.,  1., -1.],
        [ 1., -0.,  1.]])

In [25]:
# floor function
T.floor(g)

tensor([[ 0.,  0., -2.],
        [ 0., -1.,  0.]])

In [26]:
# exp function
T.exp(g)

tensor([[1.0472, 1.4954, 0.3637],
        [1.2420, 0.5421, 1.6547]])

In [27]:
# sigmoid function
T.sigmoid(g)

tensor([[0.5115, 0.5993, 0.2667],
        [0.5540, 0.3515, 0.6233]])

In [28]:
# 矩阵的点乘, x.mul(y) 或者 x * y
h = T.FloatTensor([[1,2], [3,4], [5, 6]])
print(h)
print(h.mul(h))
print(h * h)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 1.,  4.],
        [ 9., 16.],
        [25., 36.]])
tensor([[ 1.,  4.],
        [ 9., 16.],
        [25., 36.]])


In [29]:
# 矩阵相乘, x.mm(y)
print(h.mm(h.t()))

tensor([[ 5., 11., 17.],
        [11., 25., 39.],
        [17., 39., 61.]])


In [32]:
# 张量数据类型
t1 = T.tensor([1, 2], dtype=T.float32)
print(t1)
print(t1.dtype)
# 使用type()进行数据类型转换
t2 = T.tensor([1, 2], dtype=T.float32)
print(t2.dtype)
# type()方法转换数据类型
t2 = t2.type(T.int64)
print(t2)
print(t2.dtype)

tensor([1., 2.])
torch.float32
torch.float32
tensor([1, 2])
torch.int64
