In [1]:
# using pytorch to slove one variable equation
# example equation: x**2+x-1=0 .

In [2]:
# -*- coding: utf-8 -*-

import torch as T
from torch.autograd import Variable

In [3]:
# solve equation: x**2+x-1=0 .

x = Variable(T.Tensor([0.0]), requires_grad=True)

epoch = 1000
eta = 0.01

for i in range(epoch):
    # origin function
    z = (1/3) * x ** 3 + (1/2) * x ** 2 - x + 1
    z.backward()
    x.data = x.data - eta * x.grad.data
    x.grad.data.zero_()

In [4]:
print(z.data)

tensor([0.6516])


In [6]:
print(x.data)

tensor([0.6180])


In [7]:
# check if x.data is a solution of the equation
print(x.data ** 2 + x.data - 1)

tensor([-2.8610e-06])
